
- name: Retrieve secret value from AWS Parameter Store
  shell: |
    aws ssm get-parameter --name {{ public_key_path }} --region us-west-2 --with-decryption --query "Parameter.Value" --output text
    #args:
    #executable: /usr/bin/python3
  register: secret_value
#- name: Retrieve secret value from AWS Parameter Store
#  shell: "{{ playbook_dir }}/scripts/get-ssh-pub.py {{ public_key_path }}"
#  args:
#    executable: /usr/bin/python3
      ##remote_src: yes
#  register: secret_value

- name: Print registered variable
  debug:
    var: secret_value

- name: Add public key to authorized_keys for ubuntu user
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ secret_value.stdout }}"
